<?xml version="1.0"?>
<package format="3">
  <name>rsu_manager_v2</name>
  <version>0.1.0</version>
  <description>Deterministic C++ LUT-based RSU real-time control pipeline.</description>
  <maintainer email="dldnjswns7412@gmail.com">lwj</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>roa_interfaces</depend>
  <depend>realtime_tools</depend>
  <depend>ament_index_cpp</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <test_depend>ament_cmake_gtest</test_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
